version: '3.8'

services:
  # Service pour PHP et Symfony
  app:
    build:
        context: .
        dockerfile: ./docker/php/Dockerfile
    image: php:8.2-fpm
    container_name: symfony_app
    working_dir: /html
    volumes:
      - ./symfony:/html
    ports:
      - "9000:9000"
    networks:
      - symfony_network
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - db

  # Service pour Nginx
  webserver:
    image: nginx:latest
    container_name: symfony_webserver
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony_network
    depends_on:
      - app

  # Service pour MySQL
  db:
    image: mysql:8.0
    container_name: symfony_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
